$global:
  # Profiling
  # profile: True
  # profile_log_path: profile_log

  # Environment
  env:
    import: examples.envs.atari_env
    name: create_atari_env
    params:
      name: MsPacman
    frame_stack: 1
    sample_frame_stack: 80

  # Algorithm
  algorithm:
    import: onerl.algorithms
    name: DDRQNAlgorithm
    network:  # Network architecture
      feature_extractor:
        import: onerl.networks
        name: ResnetEncoder
        params:
          frame_stack: False

          in_channels: 1
          
      recurrent:
        import: onerl.networks
        name: GRURecurrent
        params:
          input_dims: 64
          hidden_dims: 256

      critic:
        import: onerl.networks
        name: MLP
        params:
          frame_stack: False

          norm_type: none
          input_dims: 256
          num_hidden: [256]
          output_dims: 9

    params:  # Algorithm hyper-parameters
      warmup_timesteps: 40  # Usually half of total BPTT timesteps

      replay_buffer_size: 1000000

      lr: 0.0002
      batch_size: 128
      gamma: 0.997

      target_update_freq: 20

      eps_start: 1.0
      eps_final: 0.1
      eps_final_steps: 10000000

  nodes:  # Metric recording node here
    MetricNode:
      num: 1

$train:
  # Training node configuration
  env:
    params:
      clip_rewards: False
      episode_life: False

  nodes:
    EnvNode:
      num: 32
    PolicyNode:
      num: 16
      batch_size: 1
      devices: [cpu]
    SchedulerNode:
      num: 1
    ReplayBufferNode:
      num: 1
    SamplerNode:
      num: 2
    OptimizerNode:
      num: 2
      update_interval: 3.0
      devices: [cuda:1, cuda:0]

$test:
  # Testing special configuration (override)
  env:
    params:
      clip_rewards: False
      episode_life: False

  algorithm:
    params:
      eps_start: 0.005
      eps_final: 0.005

  # Testing node configuration
  nodes:
    EnvNode:
      num: 1
    PolicyNode:
      num: 1
      batch_size: 1
      devices: [cpu]
      do_tick: False  # Required, prevent test steps to be counted in total steps
      optimizer_namespace: $train  # Required, specify where to load parameters
    SchedulerNode:
      num: 1
    # VisualizerNode:
    #   num: 1
